// Generated by delombok at Wed Mar 25 14:59:26 IST 2026
package com.gradetracker.service;

import com.gradetracker.exception.ResourceNotFoundException;
import com.gradetracker.model.Grade;
import com.gradetracker.model.Student;
import com.gradetracker.repository.GradeRepository;
import com.gradetracker.repository.StudentRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.util.*;
import java.util.stream.Collectors;

@Service
@Transactional
public class StudentService {
    private final StudentRepository studentRepo;
    private final GradeRepository gradeRepo;

    // ─── STUDENT CRUD ───────────────────────────────────────────────
    @Transactional(readOnly = true)
    public List<Student> getAllStudents() {
        return studentRepo.findAll();
    }

    @Transactional(readOnly = true)
    public Student getById(Long id) {
        return studentRepo.findById(id).orElseThrow(() -> new ResourceNotFoundException("Student not found with id: " + id));
    }

    public Student createStudent(Student student) {
        if (studentRepo.existsByRollNumber(student.getRollNumber())) {
            throw new IllegalArgumentException("Roll number \'" + student.getRollNumber() + "\' already exists");
        }
        return studentRepo.save(student);
    }

    public Student updateStudent(Long id, Student updated) {
        Student existing = getById(id);
        existing.setFirstName(updated.getFirstName());
        existing.setLastName(updated.getLastName());
        existing.setDepartment(updated.getDepartment());
        existing.setEmail(updated.getEmail());
        // Roll number update only if changed and not duplicate
        if (!existing.getRollNumber().equals(updated.getRollNumber())) {
            if (studentRepo.existsByRollNumber(updated.getRollNumber())) {
                throw new IllegalArgumentException("Roll number already taken");
            }
            existing.setRollNumber(updated.getRollNumber());
        }
        return studentRepo.save(existing);
    }

    public void deleteStudent(Long id) {
        if (!studentRepo.existsById(id)) {
            throw new ResourceNotFoundException("Student not found with id: " + id);
        }
        studentRepo.deleteById(id);
    }

    @Transactional(readOnly = true)
    public List<Student> searchStudents(String query) {
        if (query == null || query.trim().isEmpty()) return getAllStudents();
        return studentRepo.searchStudents(query.trim());
    }

    @Transactional(readOnly = true)
    public List<Student> getByDepartment(String department) {
        return studentRepo.findByDepartment(department);
    }

    // ─── GRADE OPERATIONS ───────────────────────────────────────────
    public Grade addGrade(Long studentId, Grade grade) {
        Student student = getById(studentId);
        grade.setStudent(student);
        return gradeRepo.save(grade);
    }

    public Grade updateGrade(Long gradeId, Grade updated) {
        Grade existing = gradeRepo.findById(gradeId).orElseThrow(() -> new ResourceNotFoundException("Grade not found: " + gradeId));
        existing.setSubject(updated.getSubject());
        existing.setMarks(updated.getMarks());
        existing.setMaxMarks(updated.getMaxMarks());
        existing.setSemester(updated.getSemester());
        existing.setExamType(updated.getExamType());
        return gradeRepo.save(existing);
    }

    public void deleteGrade(Long gradeId) {
        if (!gradeRepo.existsById(gradeId)) {
            throw new ResourceNotFoundException("Grade not found: " + gradeId);
        }
        gradeRepo.deleteById(gradeId);
    }

    // ─── ANALYTICS ──────────────────────────────────────────────────
    @Transactional(readOnly = true)
    public Map<String, Object> getAnalyticsSummary() {
        List<Student> all = studentRepo.findAll();
        long total = all.size();
        double classAvg = all.stream().filter(s -> !s.getGrades().isEmpty()).mapToDouble(Student::getAveragePercentage).average().orElse(0.0);
        long distinction = all.stream().filter(s -> s.getAveragePercentage() >= 80).count();
        long failing = all.stream().filter(s -> !s.getGrades().isEmpty() && s.getAveragePercentage() < 50).count();
        // Grade distribution
        Map<String, Long> distribution = new LinkedHashMap<>();
        distribution.put("A+", all.stream().filter(s -> s.getAveragePercentage() >= 90).count());
        distribution.put("A", all.stream().filter(s -> {
            double a = s.getAveragePercentage();
            return a >= 80 && a < 90;
        }).count());
        distribution.put("B", all.stream().filter(s -> {
            double a = s.getAveragePercentage();
            return a >= 70 && a < 80;
        }).count());
        distribution.put("C", all.stream().filter(s -> {
            double a = s.getAveragePercentage();
            return a >= 60 && a < 70;
        }).count());
        distribution.put("D", all.stream().filter(s -> {
            double a = s.getAveragePercentage();
            return a >= 50 && a < 60;
        }).count());
        distribution.put("F", all.stream().filter(s -> !s.getGrades().isEmpty() && s.getAveragePercentage() < 50).count());
        // Department averages
        Map<String, Double> deptAvg = all.stream().filter(s -> s.getDepartment() != null && !s.getGrades().isEmpty()).collect(Collectors.groupingBy(Student::getDepartment, Collectors.averagingDouble(Student::getAveragePercentage)));
        // Top 5 students
        List<Map<String, Object>> toppers = all.stream().filter(s -> !s.getGrades().isEmpty()).sorted(Comparator.comparingDouble(Student::getAveragePercentage).reversed()).limit(5).map(s -> {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("id", s.getId());
            m.put("name", s.getFirstName() + " " + s.getLastName());
            m.put("rollNumber", s.getRollNumber());
            m.put("department", s.getDepartment());
            m.put("average", Math.round(s.getAveragePercentage() * 10.0) / 10.0);
            m.put("grade", s.getOverallGrade());
            return m;
        }).collect(Collectors.toList());
        Map<String, Object> result = new LinkedHashMap<>();
        result.put("totalStudents", total);
        result.put("classAverage", Math.round(classAvg * 10.0) / 10.0);
        result.put("distinction", distinction);
        result.put("failing", failing);
        result.put("gradeDistribution", distribution);
        result.put("departmentAverages", deptAvg);
        result.put("toppers", toppers);
        return result;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public StudentService(final StudentRepository studentRepo, final GradeRepository gradeRepo) {
        this.studentRepo = studentRepo;
        this.gradeRepo = gradeRepo;
    }
}
