// Generated by delombok at Wed Mar 25 14:59:26 IST 2026
package com.gradetracker.controller;

import com.gradetracker.model.Grade;
import com.gradetracker.model.Student;
import com.gradetracker.service.StudentService;
import jakarta.validation.Valid;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import java.util.List;
import java.util.Map;

@RestController
@RequestMapping("/api")
@CrossOrigin(origins = {"http://localhost:3000", "http://localhost:5173"})
public class StudentController {
    private final StudentService service;

    // ─── STUDENT ENDPOINTS ──────────────────────────────────────────
    /**
     * GET /api/students — get all students
     */
    @GetMapping("/students")
    public ResponseEntity<List<Student>> getAllStudents() {
        return ResponseEntity.ok(service.getAllStudents());
    }

    /**
     * GET /api/students/{id} — get single student
     */
    @GetMapping("/students/{id}")
    public ResponseEntity<Student> getStudent(@PathVariable Long id) {
        return ResponseEntity.ok(service.getById(id));
    }

    /**
     * GET /api/students/search?q=... — search students
     */
    @GetMapping("/students/search")
    public ResponseEntity<List<Student>> searchStudents(@RequestParam(defaultValue = "") String q) {
        return ResponseEntity.ok(service.searchStudents(q));
    }

    /**
     * GET /api/students/department/{dept} — filter by department
     */
    @GetMapping("/students/department/{dept}")
    public ResponseEntity<List<Student>> getByDepartment(@PathVariable String dept) {
        return ResponseEntity.ok(service.getByDepartment(dept));
    }

    /**
     * POST /api/students — create new student
     */
    @PostMapping("/students")
    public ResponseEntity<Student> createStudent(@Valid @RequestBody Student student) {
        Student saved = service.createStudent(student);
        return ResponseEntity.status(HttpStatus.CREATED).body(saved);
    }

    /**
     * PUT /api/students/{id} — update student
     */
    @PutMapping("/students/{id}")
    public ResponseEntity<Student> updateStudent(@PathVariable Long id, @Valid @RequestBody Student student) {
        return ResponseEntity.ok(service.updateStudent(id, student));
    }

    /**
     * DELETE /api/students/{id} — delete student
     */
    @DeleteMapping("/students/{id}")
    public ResponseEntity<Map<String, String>> deleteStudent(@PathVariable Long id) {
        service.deleteStudent(id);
        return ResponseEntity.ok(Map.of("message", "Student deleted successfully"));
    }

    // ─── GRADE ENDPOINTS ────────────────────────────────────────────
    /**
     * POST /api/students/{id}/grades — add grade to student
     */
    @PostMapping("/students/{id}/grades")
    public ResponseEntity<Grade> addGrade(@PathVariable Long id, @Valid @RequestBody Grade grade) {
        Grade saved = service.addGrade(id, grade);
        return ResponseEntity.status(HttpStatus.CREATED).body(saved);
    }

    /**
     * PUT /api/grades/{gradeId} — update a grade
     */
    @PutMapping("/grades/{gradeId}")
    public ResponseEntity<Grade> updateGrade(@PathVariable Long gradeId, @Valid @RequestBody Grade grade) {
        return ResponseEntity.ok(service.updateGrade(gradeId, grade));
    }

    /**
     * DELETE /api/grades/{gradeId} — delete a grade
     */
    @DeleteMapping("/grades/{gradeId}")
    public ResponseEntity<Map<String, String>> deleteGrade(@PathVariable Long gradeId) {
        service.deleteGrade(gradeId);
        return ResponseEntity.ok(Map.of("message", "Grade deleted successfully"));
    }

    // ─── ANALYTICS ENDPOINT ─────────────────────────────────────────
    /**
     * GET /api/analytics — full analytics summary
     */
    @GetMapping("/analytics")
    public ResponseEntity<Map<String, Object>> getAnalytics() {
        return ResponseEntity.ok(service.getAnalyticsSummary());
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public StudentController(final StudentService service) {
        this.service = service;
    }
}
