// Generated by delombok at Wed Mar 25 14:59:26 IST 2026
package com.gradetracker.model;

import com.fasterxml.jackson.annotation.JsonBackReference;
import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.*;

@Entity
@Table(name = "grades")
public class Grade {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @NotBlank(message = "Subject is required")
    @Column(nullable = false)
    private String subject;
    @Min(value = 0, message = "Marks cannot be negative")
    @Column(nullable = false)
    private int marks;
    @Min(value = 1, message = "Max marks must be at least 1")
    @Column(nullable = false)
    private int maxMarks;
    private String semester;
    private String examType; // e.g., "Mid-term", "Final", "Assignment"
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "student_id", nullable = false)
    @JsonBackReference
    private Student student;

    // Computed fields
    @Transient
    public double getPercentage() {
        return Math.round((marks * 100.0 / maxMarks) * 10.0) / 10.0;
    }

    @Transient
    public String getLetterGrade() {
        double pct = getPercentage();
        if (pct >= 90) return "A+";
        if (pct >= 80) return "A";
        if (pct >= 70) return "B";
        if (pct >= 60) return "C";
        if (pct >= 50) return "D";
        return "F";
    }


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class GradeBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Long id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String subject;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private int marks;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private int maxMarks;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String semester;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String examType;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Student student;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        GradeBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Grade.GradeBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Grade.GradeBuilder subject(final String subject) {
            this.subject = subject;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Grade.GradeBuilder marks(final int marks) {
            this.marks = marks;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Grade.GradeBuilder maxMarks(final int maxMarks) {
            this.maxMarks = maxMarks;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Grade.GradeBuilder semester(final String semester) {
            this.semester = semester;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Grade.GradeBuilder examType(final String examType) {
            this.examType = examType;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Grade.GradeBuilder student(final Student student) {
            this.student = student;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Grade build() {
            return new Grade(this.id, this.subject, this.marks, this.maxMarks, this.semester, this.examType, this.student);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "Grade.GradeBuilder(id=" + this.id + ", subject=" + this.subject + ", marks=" + this.marks + ", maxMarks=" + this.maxMarks + ", semester=" + this.semester + ", examType=" + this.examType + ", student=" + this.student + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static Grade.GradeBuilder builder() {
        return new Grade.GradeBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getSubject() {
        return this.subject;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int getMarks() {
        return this.marks;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int getMaxMarks() {
        return this.maxMarks;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getSemester() {
        return this.semester;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getExamType() {
        return this.examType;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Student getStudent() {
        return this.student;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSubject(final String subject) {
        this.subject = subject;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setMarks(final int marks) {
        this.marks = marks;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setMaxMarks(final int maxMarks) {
        this.maxMarks = maxMarks;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setSemester(final String semester) {
        this.semester = semester;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setExamType(final String examType) {
        this.examType = examType;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setStudent(final Student student) {
        this.student = student;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Grade)) return false;
        final Grade other = (Grade) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.getMarks() != other.getMarks()) return false;
        if (this.getMaxMarks() != other.getMaxMarks()) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$subject = this.getSubject();
        final java.lang.Object other$subject = other.getSubject();
        if (this$subject == null ? other$subject != null : !this$subject.equals(other$subject)) return false;
        final java.lang.Object this$semester = this.getSemester();
        final java.lang.Object other$semester = other.getSemester();
        if (this$semester == null ? other$semester != null : !this$semester.equals(other$semester)) return false;
        final java.lang.Object this$examType = this.getExamType();
        final java.lang.Object other$examType = other.getExamType();
        if (this$examType == null ? other$examType != null : !this$examType.equals(other$examType)) return false;
        final java.lang.Object this$student = this.getStudent();
        final java.lang.Object other$student = other.getStudent();
        if (this$student == null ? other$student != null : !this$student.equals(other$student)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Grade;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + this.getMarks();
        result = result * PRIME + this.getMaxMarks();
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $subject = this.getSubject();
        result = result * PRIME + ($subject == null ? 43 : $subject.hashCode());
        final java.lang.Object $semester = this.getSemester();
        result = result * PRIME + ($semester == null ? 43 : $semester.hashCode());
        final java.lang.Object $examType = this.getExamType();
        result = result * PRIME + ($examType == null ? 43 : $examType.hashCode());
        final java.lang.Object $student = this.getStudent();
        result = result * PRIME + ($student == null ? 43 : $student.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "Grade(id=" + this.getId() + ", subject=" + this.getSubject() + ", marks=" + this.getMarks() + ", maxMarks=" + this.getMaxMarks() + ", semester=" + this.getSemester() + ", examType=" + this.getExamType() + ", student=" + this.getStudent() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Grade() {
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Grade(final Long id, final String subject, final int marks, final int maxMarks, final String semester, final String examType, final Student student) {
        this.id = id;
        this.subject = subject;
        this.marks = marks;
        this.maxMarks = maxMarks;
        this.semester = semester;
        this.examType = examType;
        this.student = student;
    }
}
