// Generated by delombok at Wed Mar 25 14:59:26 IST 2026
package com.gradetracker.model;

import com.fasterxml.jackson.annotation.JsonManagedReference;
import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.*;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "students")
public class Student {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @NotBlank(message = "First name is required")
    @Column(nullable = false)
    private String firstName;
    @NotBlank(message = "Last name is required")
    @Column(nullable = false)
    private String lastName;
    @NotBlank(message = "Roll number is required")
    @Column(unique = true, nullable = false)
    private String rollNumber;
    private String department;
    @Email(message = "Please enter a valid email")
    private String email;
    @Column(updatable = false)
    private LocalDateTime createdAt;
    @OneToMany(mappedBy = "student", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.EAGER)
    @JsonManagedReference
    private List<Grade> grades;

    @PrePersist
    public void prePersist() {
        this.createdAt = LocalDateTime.now();
    }

    // Computed: average percentage across all grades
    @Transient
    public double getAveragePercentage() {
        if (grades == null || grades.isEmpty()) return 0.0;
        return grades.stream().mapToDouble(g -> (g.getMarks() * 100.0) / g.getMaxMarks()).average().orElse(0.0);
    }

    // Computed: overall letter grade
    @Transient
    public String getOverallGrade() {
        double avg = getAveragePercentage();
        if (avg >= 90) return "A+";
        if (avg >= 80) return "A";
        if (avg >= 70) return "B";
        if (avg >= 60) return "C";
        if (avg >= 50) return "D";
        if (avg > 0) return "F";
        return "N/A";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    private static List<Grade> $default$grades() {
        return new ArrayList<>();
    }


    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static class StudentBuilder {
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private Long id;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String firstName;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String lastName;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String rollNumber;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String department;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private String email;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private LocalDateTime createdAt;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private boolean grades$set;
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        private List<Grade> grades$value;

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        StudentBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Student.StudentBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Student.StudentBuilder firstName(final String firstName) {
            this.firstName = firstName;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Student.StudentBuilder lastName(final String lastName) {
            this.lastName = lastName;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Student.StudentBuilder rollNumber(final String rollNumber) {
            this.rollNumber = rollNumber;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Student.StudentBuilder department(final String department) {
            this.department = department;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Student.StudentBuilder email(final String email) {
            this.email = email;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Student.StudentBuilder createdAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Student.StudentBuilder grades(final List<Grade> grades) {
            this.grades$value = grades;
            grades$set = true;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public Student build() {
            List<Grade> grades$value = this.grades$value;
            if (!this.grades$set) grades$value = Student.$default$grades();
            return new Student(this.id, this.firstName, this.lastName, this.rollNumber, this.department, this.email, this.createdAt, grades$value);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        @lombok.Generated
        public java.lang.String toString() {
            return "Student.StudentBuilder(id=" + this.id + ", firstName=" + this.firstName + ", lastName=" + this.lastName + ", rollNumber=" + this.rollNumber + ", department=" + this.department + ", email=" + this.email + ", createdAt=" + this.createdAt + ", grades$value=" + this.grades$value + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public static Student.StudentBuilder builder() {
        return new Student.StudentBuilder();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getFirstName() {
        return this.firstName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getLastName() {
        return this.lastName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getRollNumber() {
        return this.rollNumber;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getDepartment() {
        return this.department;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public String getEmail() {
        return this.email;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public List<Grade> getGrades() {
        return this.grades;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setFirstName(final String firstName) {
        this.firstName = firstName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setLastName(final String lastName) {
        this.lastName = lastName;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setRollNumber(final String rollNumber) {
        this.rollNumber = rollNumber;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setDepartment(final String department) {
        this.department = department;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setEmail(final String email) {
        this.email = email;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setGrades(final List<Grade> grades) {
        this.grades = grades;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Student)) return false;
        final Student other = (Student) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$firstName = this.getFirstName();
        final java.lang.Object other$firstName = other.getFirstName();
        if (this$firstName == null ? other$firstName != null : !this$firstName.equals(other$firstName)) return false;
        final java.lang.Object this$lastName = this.getLastName();
        final java.lang.Object other$lastName = other.getLastName();
        if (this$lastName == null ? other$lastName != null : !this$lastName.equals(other$lastName)) return false;
        final java.lang.Object this$rollNumber = this.getRollNumber();
        final java.lang.Object other$rollNumber = other.getRollNumber();
        if (this$rollNumber == null ? other$rollNumber != null : !this$rollNumber.equals(other$rollNumber)) return false;
        final java.lang.Object this$department = this.getDepartment();
        final java.lang.Object other$department = other.getDepartment();
        if (this$department == null ? other$department != null : !this$department.equals(other$department)) return false;
        final java.lang.Object this$email = this.getEmail();
        final java.lang.Object other$email = other.getEmail();
        if (this$email == null ? other$email != null : !this$email.equals(other$email)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        final java.lang.Object this$grades = this.getGrades();
        final java.lang.Object other$grades = other.getGrades();
        if (this$grades == null ? other$grades != null : !this$grades.equals(other$grades)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Student;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $firstName = this.getFirstName();
        result = result * PRIME + ($firstName == null ? 43 : $firstName.hashCode());
        final java.lang.Object $lastName = this.getLastName();
        result = result * PRIME + ($lastName == null ? 43 : $lastName.hashCode());
        final java.lang.Object $rollNumber = this.getRollNumber();
        result = result * PRIME + ($rollNumber == null ? 43 : $rollNumber.hashCode());
        final java.lang.Object $department = this.getDepartment();
        result = result * PRIME + ($department == null ? 43 : $department.hashCode());
        final java.lang.Object $email = this.getEmail();
        result = result * PRIME + ($email == null ? 43 : $email.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        final java.lang.Object $grades = this.getGrades();
        result = result * PRIME + ($grades == null ? 43 : $grades.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "Student(id=" + this.getId() + ", firstName=" + this.getFirstName() + ", lastName=" + this.getLastName() + ", rollNumber=" + this.getRollNumber() + ", department=" + this.getDepartment() + ", email=" + this.getEmail() + ", createdAt=" + this.getCreatedAt() + ", grades=" + this.getGrades() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Student() {
        this.grades = Student.$default$grades();
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Student(final Long id, final String firstName, final String lastName, final String rollNumber, final String department, final String email, final LocalDateTime createdAt, final List<Grade> grades) {
        this.id = id;
        this.firstName = firstName;
        this.lastName = lastName;
        this.rollNumber = rollNumber;
        this.department = department;
        this.email = email;
        this.createdAt = createdAt;
        this.grades = grades;
    }
}
