// Generated by delombok at Wed Mar 25 14:59:26 IST 2026
package com.gradetracker;

import com.gradetracker.model.Grade;
import com.gradetracker.model.Student;
import com.gradetracker.repository.GradeRepository;
import com.gradetracker.repository.StudentRepository;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;
import java.util.List;

@Component
public class DataInitializer implements CommandLineRunner {
    private final StudentRepository studentRepo;
    private final GradeRepository gradeRepo;

    @Override
    public void run(String... args) {
        // Add sample students with grades so the app is not empty on start
        Student s1 = studentRepo.save(Student.builder().firstName("Aarav").lastName("Sharma").rollNumber("CS001").department("Computer Science").email("aarav.sharma@college.edu").build());
        Student s2 = studentRepo.save(Student.builder().firstName("Priya").lastName("Reddy").rollNumber("CS002").department("Electronics").email("priya.reddy@college.edu").build());
        Student s3 = studentRepo.save(Student.builder().firstName("Rahul").lastName("Verma").rollNumber("MT001").department("Mathematics").email("rahul.verma@college.edu").build());
        Student s4 = studentRepo.save(Student.builder().firstName("Sneha").lastName("Patel").rollNumber("CS003").department("Computer Science").email("sneha.patel@college.edu").build());
        // Grades for Aarav
        gradeRepo.saveAll(List.of(Grade.builder().subject("Mathematics").marks(88).maxMarks(100).semester("Sem 1").examType("Final").student(s1).build(), Grade.builder().subject("Physics").marks(75).maxMarks(100).semester("Sem 1").examType("Final").student(s1).build(), Grade.builder().subject("Computer Science").marks(95).maxMarks(100).semester("Sem 1").examType("Final").student(s1).build(), Grade.builder().subject("English").marks(82).maxMarks(100).semester("Sem 1").examType("Final").student(s1).build()));
        // Grades for Priya
        gradeRepo.saveAll(List.of(Grade.builder().subject("Mathematics").marks(92).maxMarks(100).semester("Sem 1").examType("Final").student(s2).build(), Grade.builder().subject("Physics").marks(85).maxMarks(100).semester("Sem 1").examType("Final").student(s2).build(), Grade.builder().subject("Chemistry").marks(78).maxMarks(100).semester("Sem 1").examType("Final").student(s2).build()));
        // Grades for Rahul
        gradeRepo.saveAll(List.of(Grade.builder().subject("Mathematics").marks(97).maxMarks(100).semester("Sem 1").examType("Final").student(s3).build(), Grade.builder().subject("Statistics").marks(91).maxMarks(100).semester("Sem 1").examType("Final").student(s3).build()));
        // Grades for Sneha
        gradeRepo.saveAll(List.of(Grade.builder().subject("Computer Science").marks(72).maxMarks(100).semester("Sem 1").examType("Final").student(s4).build(), Grade.builder().subject("Mathematics").marks(68).maxMarks(100).semester("Sem 1").examType("Final").student(s4).build(), Grade.builder().subject("English").marks(80).maxMarks(100).semester("Sem 1").examType("Final").student(s4).build()));
        System.out.println("  Sample data loaded: 4 students, 12 grades");
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public DataInitializer(final StudentRepository studentRepo, final GradeRepository gradeRepo) {
        this.studentRepo = studentRepo;
        this.gradeRepo = gradeRepo;
    }
}
